### ISSUE TITLE
Change behavior for placeholder attribute

### ISSUE THREAD

**Issue by kasparsklavins** [Limenius/Liform#17]
From `README.md`:
> If the attribute placeholder of attr is provided [...] It will be extracted as the default option.

According to html5 spec[0], placeholders are meant as hints for the input, and may contain a non-valid value
> The placeholder attribute represents a short hint (a word or short phrase) intended to aid the user with data entry. A hint could be a sample value or a brief description of the expected format

**I propose removing the feature of using  placeholder attribute for a default value.** 

[0] https://www.w3.org/TR/2011/WD-html5-20110405/common-input-element-attributes.html#the-placeholder-attribute

**Comment by nacmartin** [comment]
Uhm, yes, I think that this is right. Pass it as an extra attribute out of the specification would be better so the client can use it or not.

**Comment by kasparsklavins** [comment]
I can do a PR for this.
Is there any contributing policy?

**Comment by nacmartin** [comment]
Oh, thanks! Not really. It would be nice to add a test, though :)
