### ISSUE TITLE
new transformers

### ISSUE THREAD

**Issue by omarsoufiane** [Limenius/Liform#2]
transformers are not clear in the documentation and i don't know what i should do to create a new one for FileType to handle image uploads

**Comment by nacmartin** [comment]
I have recently done an example of uploading images. Uploading files in an API context is always annoying, but maybe this works for you. It is about having a string type where we receive files encoded in base64.

There is a data transformer: https://github.com/Limenius/symfony-react-sandbox/tree/master/src/AppBundle/Form/DataTransformer

That transforms base64->file.

Then there is a listener here that uploads the file to the right place:
https://github.com/Limenius/symfony-react-sandbox/blob/master/src/AppBundle/EventListener/ImageUploadListener.php 

Similar to [what is in the symfony docs](http://symfony.com/doc/current/controller/upload_file.html)

And I simply use String transformer setting `widget` file: https://github.com/Limenius/symfony-react-sandbox/blob/master/src/AppBundle/Form/Type/RecipeType.php

I take note about the documentation. I think it would be nice to write a blog post about uploading files in an API, (explaining this), and also to explain more about transformers.

**Comment by omarsoufiane** [comment]
thank you man you saved my life, you are my hero, i really like the way you modernized how we work with the front end in symfony

**Comment by nacmartin** [comment]
Thank you very much, @omarsoufiane  :)

**Comment by comemanu** [comment]
@nacmartin thank you too ! that's so useful and quick to use this code.
