### ISSUE TITLE
Outdated readme using setDefaultTransformers

### ISSUE THREAD

**Issue by kasparsklavins** [Limenius/Liform#24]
In this commit https://github.com/Limenius/Liform/commit/09031023f40ba21a8c62019647c8b5619c350217 the method `setDefaultTransformers` was removed, making [Usage ](https://github.com/Limenius/Liform#usage)example incorrect.

The readme should be updated to reflect how Liform has to be initiated now.

**Comment by nacmartin** [comment]
Thanks for reporting this, @kasparsklavins! fixed. It was a nice way of using the library without the bundle, but at the end it was inconvenient :(
