### ISSUE TITLE
Still in Use?

### ISSUE THREAD

**Issue by Psiiirus** [Limenius/Liform#32]
Hiya,
i was wondering if this is still in use by limenius and is this still under maintaince?
Would be nice to know if the symfony bundle will be support flex / symfony 4?

Cheers,
Toni

**Comment by nacmartin** [comment]
Hi, @MM-Psiiirus yes, we use it. However, in our case we use a pretty particular theme for our project, so many of the issues reported don't affect us.

I am hoping to find more time soon to address the issues that have been reported. Probably during June, as I will hopefully have some free time. Thanks for the interest

**Comment by Psiiirus** [comment]
Thanks for the fast answer :)

I wasn't really talking about the open issues than about the last commit timestamp but if everything is working fine with newest symfony versions and is still in productive use I am happy take a deeper look into LiForm and LiForm-react. ;)

Cheers!

**Comment by nacmartin** [comment]
Sure, it was tested with Symfony 4 during the release of Symfony 4. https://github.com/Limenius/Liform/commit/107ee98907604181ec705c8422d2a0bdbded4482#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

Basically the issue with maintenance is that... this is working well for us, and we consider the pieces where is used "stable" pieces, that work well for for our use (currently used in two projects). Then, in this situation, I kind of have to allocate free time to work on features or issues that don't directly affect us, and I can do it some times, but in the last months I have been too busy :/. Hope to change that soon.
