### ISSUE TITLE
why   isRequire  method of AbstractTransfomer  is called successfully outside of the class it is in since it is protected? 

### ISSUE THREAD

**Issue by videni** [Limenius/Liform#40]
$transformerData['transformer']   is an instance of AbstractTransfomer, and the isRequired method is protected , I also don't find any hack way,   why does this line works? this is  quite strange. 

https://github.com/Limenius/Liform/blob/b46ba76cc7703b9d9989ff9f8ca4437cfc8f6c6c/src/Limenius/Liform/Transformer/CompoundTransformer.php#L60

**Comment by jrbarnard** [comment]
As it's called from within another subclass of AbstractTransformer you can call protected methods of other classes (I didn't realise this but just testing with the following code if you want to try):

```
abstract class TestClass
{
    protected $test = 'hello';
    public function __construct($test = null)
    {
         if ($test) {
             $this->test = $test;
         }
     } 
     protected function testing($arg)
     {
         return $arg . $this->test;
     }
     public function call($child, $arg)
     {
         return $child->testing($arg);
     }
}

class Child extends TestClass
{
    //
}

$childOne = new Child('world');
$childTwo = new Child('testing');

// Get child two to internally call child one's testing method with the passed argument.
$childTwo->call($childOne, 'woah');
// Will return 'woahworld' and not throw an error
```

If you call it externally or from a non sub class it will throw, e.g:
```
class Another
{
    protected function call($child, $arg)
    {
        return $child->testing($arg);
    }
}

$another = new Another()
$another->call($childOne, 'woah');
// PHP Error:  Call to protected method TestClass::testing() from context 'Another'
```

Not . sure if would be better as a public method, I suppose it would be clearer?

**Comment by nacmartin** [comment]
That is right, it is clearer, fixed, thanks!
