### ISSUE TITLE
[Feature] Use 'help' defined on form to render as description

### ISSUE THREAD

**Issue by jrbarnard** [Limenius/Liform#42]
Currently to output a 'description' it required setting the 'description' key within the 'liform' form option, however I think it would be good if it would use the help key (from Symfony 4.1) and then override with the liform description value if it's set? (Similarly to the widget override).

I'm happy to do a PR + tests for this.

**Comment by nacmartin** [comment]
Manally merged in https://github.com/Limenius/Liform/commit/6415c70544162b26cb2bd0b39961e78f5e55f3df
