### ISSUE TITLE
Notice: Undefined index: compound

### ISSUE THREAD

**Issue by Adraesh** [Limenius/Liform#48]
Hi!

I am probably not doing properly the thing as it should be done, but I prefer to ask.

I am simply trying to get the json structure of a simple form as following:

```
$builder
            ->add('name', TextType::class)
            ->add('owner', EntityType::class, [
                'class' => User::class, 'choice_label' => 'email'
            ])
            ->add('coop', EntityType::class, [
                'class' => Coop::class, 'choice_label' => 'name'
            ])
        ;
```

```
$restaurant = new Restaurant();

        $resolver = new Resolver();
        $liform = new Liform($resolver);

        $form = $this->createForm(RestaurantType::class, $restaurant, ['csrf_protection' => false]);
        $schema = json_encode($liform->transform($form));

        die(var_dump($schema));
```

From the doc, I really don't understand the part where the setTransformer is done on the resolver. Does this part is mandatory? How this part as to be done properly?

Thank you in advance.

**Comment by Adraesh** [comment]
EDIT: Problem solved by using the liformbundle for symfony and injecting the Liform into my function.

**Comment by SanderVanCamp** [comment]
hey @Adraesh , could you copy paste the whole solution? I can't get it to work! Thank you very much! Kind regards,
Sander

**Comment by Adraesh** [comment]
@SanderVanCamp I used this bundle: https://github.com/Limenius/LiformBundle and especially:

`
$form = $this->createForm(CarType::class, $car, ['csrf_protection' => false]);
`
`
$schema = json_encode($this->get('liform')->transform($form));
`
