### ISSUE TITLE
[Update] symfony/form 4.4 - 5.0

### ISSUE THREAD

**Issue by mokabyls** [Limenius/Liform#49]
Have you any plan to update your library and made it compatible with symfony/form ^4.4 | ^5.0 ? 
I'll plan to use your library but cannot install it because of symfony/form version.

**Comment by GinoPane** [comment]
Same here

**Comment by demroos** [comment]
I have the same problem.

**Comment by 20uf** [comment]
Same here, thanks to @demroos for doing a PR #51 _(which needs a little PHPCS correction at the moment)_

**Comment by in0de** [comment]
I'm using symfony 5.1 and was able to install it no problem. What's the error message you are getting?

**Comment by nacmartin** [comment]
Done in dev-master, will release a new version soon.
