### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by JonnyAxehandle** [Limenius/Liform#63]
No updates in 16 months. I need this for a project running on PHP8 but can't cause all the PRs are in limbo

**Comment by ntoniazzi** [comment]
This project is abandoned, and unfortunately, there is not a unique fork. You'll have to choose a project, without a better guaranty that it's actively maintained.
https://packagist.org/?query=liform&type=library

**Comment by malarzm** [comment]
FWIW we've ended with a fork we're going to maintain for the time being: https://github.com/answear/Liform

**Comment by laurent-bientz** [comment]
Hello, 

If you're interested in an alternative, we've created https://github.com/w3r-one/json-schema-bundle/ from scratch.

Feel free to take a look.

Not all the json-schema is implemented but all the features covered by Liform are ok and compliant with the RFC.

**Comment by nacmartin** [comment]
PHP8 is supported.
