### ISSUE TITLE
allow Symfony 6

### ISSUE THREAD

**Issue by tacman** [Limenius/Liform#65]
Symfony 6 would be great.  Related to #56 , since it requires php8.

**Comment by tacman** [comment]
I have this working on my branch with Symfony 6.  Will you accept a PR?

**Comment by malarzm** [comment]
FWIW we've ended with a fork we're going to maintain for the time being: https://github.com/answear/Liform

**Comment by tacman** [comment]
Thanks!  Is there a fork of LiformBundle that uses that (forked) library?

**Comment by tacman** [comment]
Ah, found it! https://github.com/answear/LiformBundle
