### ISSUE TITLE
Labels not being translated

### ISSUE THREAD

**Issue by jrmyio** [Limenius/Liform#8]
It seems that currently the Labels are not translated. A Field has a TranslationDomain in symfony that can be used to overwrite the default NULL (which resolves to "messages").
http://symfony.com/doc/current/reference/forms/types/form.html#translation-domain

Can be integrated the same way the Error Translation is done, in file:
https://github.com/Limenius/Liform/blob/master/src/Limenius/Liform/Transformer/AbstractTransformer.php

It might also be useful for [liform][description].

**Comment by nacmartin** [comment]
Thanks @ConneXNL. Indeed it was needed.

Should be fixed in master. Let me update the bundle and release a new version with this.

**Comment by nacmartin** [comment]
v0.10.1 contains this change. It ended being up a bigger change than was expected, but it should work.
