### ISSUE TITLE
Add constraints defined in form type

### ISSUE THREAD

**Issue by lucasgranberg** [Limenius/Liform#9]
I have my constraints defined directly in my form and not in the entity. 

Would it be possible to add the constraints from the form if there is no constraints on the entity?

**Comment by jrbarnard** [comment]
I got around this by having a ConstraintExtension that will loop over the set constraints and run them through custom constraint -> schema transformers that I've written.
It looks like the underlying ValidationGuesser stuff doesn't work with Form Type constraints.

I'd like to see a system in core that would support this with default transformers.

For instance:
- Define Constraint Transformers as you do with extensions (tagging services) so they get loaded
- As part of the Abstract Transformer (before ->applyExtensions()) call applyConstraints() which will loop the set constraints on the form and locate & apply the individual Transformer classes for each Constraint updating the Schema.

We'd need a bunch of default transformers, e.g LengthTransformer min / max apply to string types, minLength and maxLength keys.

I'd be happy to do a PR with a few initial transformers which could then be added to in the future.

**Comment by domhaas** [comment]
> I got around this by having a ConstraintExtension that will loop over the set constraints and run them through custom constraint -> schema transformers that I've written.
> It looks like the underlying ValidationGuesser stuff doesn't work with Form Type constraints.
> 
> I'd like to see a system in core that would support this with default transformers.
> 
> For instance:
> 
>     * Define Constraint Transformers as you do with extensions (tagging services) so they get loaded
> 
>     * As part of the Abstract Transformer (before ->applyExtensions()) call applyConstraints() which will loop the set constraints on the form and locate & apply the individual Transformer classes for each Constraint updating the Schema.
> 
> 
> We'd need a bunch of default transformers, e.g LengthTransformer min / max apply to string types, minLength and maxLength keys.
> 
> I'd be happy to do a PR with a few initial transformers which could then be added to in the future.

@jrbarnard I'm currently stuck on the the same point. I'm not using annotation-constraints cause of trying to keep the entities generic.
Do you got some code to share for your constraint-extension? Thank you in advance.

Btw, this extension is really helpful. I'm using it together with the [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form), but needed to make some customizations. Hoping to find time to share my changes.

**Comment by jrbarnard** [comment]
@domhaas The code I've got is in a private repo but here is a rough rewritten version:

In reality I have a ConstraintTransformer that handles the job of identifying the type of Constraint and schema and what transformation to do to keep it cleaner and easier to test.

```
class FormConstraintExtension implements \Limenius\Liform\Transformer\ExtensionInterface
{
    public function apply(\Symfony\Component\Form\FormInterface $form, array $schema)
    {
        // Get the constraints set directly against the form / field
        $constraints = $form->getConfig()->getOption('constraints', []);

        // Loop the form constraints
        foreach ($constraints as $constraint) {
            // Apply the schema transformation
            // Single example of a count constraint on an array
            // Add more as needed
            if ($constraint instanceof \Symfony\Component\Validator\Constraints\Count && $schema['type'] === 'array') {
                $schema['minItems'] = $constraint->min;
                $schema['maxItems'] = $constraint->max;
            }
        }

        return $schema;
    }
}
```

This extension would need to be registered as in the docs (for symfony framework: Symfony\Component\Validator\Constraints\Count)

I hope that helps
